% ECE478 Financial Signal Processing
% Yilun Jiang
% Basic Markovitz Portfolio Analysis

clear;
%% wrapper code to import data
filename = '48_Industry_Portofolios_daily_2008.txt';
filename1 = 'SP500_daily_index_2008.txt';
delimiterIn = ' ';
delimiterIn1 = '\n';
A = importdata(filename,delimiterIn);
SP500 = importdata(filename1, delimiterIn1);
A(:,1) = []; % delete the date information from the file
A = A.';
missing = 0;
for i = 1:numel(A)
  if A(i) == -99.99 || A(i) == -999
      A(i) = A(i+48); %if data is missing for one day, just set it equal to the next day return
      missing = missing + 1;
  end
end
txt = ['total number of missing data is ', num2str(missing)];
disp(txt);

%% Question A
MeanVector = mean(A,2); % M is the mean vector
MeanMatrix = zeros(48, 250);
for i = 1:250
    MeanMatrix(:,i) = MeanVector; %create
end
Cov = 1/251*(A*A'- MeanMatrix*MeanMatrix'); % Cov is the covariance matrix

%% Question B
%The MVP portfolio
oneVector = ones(48,1);
riskMVP = (oneVector'* inv(Cov) * oneVector).^(-0.5);
weightMVP = riskMVP.^2 * inv(Cov) * oneVector;
returnMVP = weightMVP' * MeanVector;
%The naive portfolio
weightNaive = zeros(48,1);
for i = 1:numel(weightNaive)
    weightNaive(i) = 1/48;
end
returnNaive = weightNaive' * MeanVector;
riskNaive = sqrt(weightNaive'* Cov * weightNaive);
%The market portfolio
% since my MeanVector and Covariance matrix is calculated on a daily basis
% I am converting the annual LIBOR I found online to a daily basis
% I found the closing S&P500 index for each day in 2008 so through
% dividing index for day i+1 by index for day i and minus 1 the result is 
% automatically in a daily basis.
dailyR =100*((1+2.326/100)^(1/251)-1);
dailyReturnSP500 = zeros(251,1);
for i = 1:251
    dailyReturnSP500(i) = (SP500(i+1)/SP500(i) - 1)*100; %this calculates the daily return of SP500
end
ReturnSP500 = sum(dailyReturnSP500) / 251 ; %mean return of SP500 in percentage
riskSP500 = 1/250 * sum((dailyReturnSP500-ReturnSP500).^2); %risk of market portfolio is the variance of SP500
%Portfolio with two securities
%The covariance matrix for each pair of securities is obtained by selecting 
%relevant entries from the 48*48 covariance matrix
%The column numbers for the five pairs I chose are stored in the trial matrix.
%Each row indicate one pair of securities.
oneVector = ones(2,1);
covPair = zeros(2,2); %covPair will be the covariance matrix for the first pair
MeanPair = zeros(2,1); %MeanPair wll be the mean return vector for the first pair
trial = [1 11, 5 41, 6 17, 10 19, 27 39]; %Five random pairs I chose to process
x = 0:0.1:10; % x is the risk value
y = zeros(5, 101); % y is the return value calculated in each risk value
for i = 1:5 
    covPair(1,1) = Cov(trial(i),trial(i)); 
    %trial(i) & trial(i+5) are one row in the trial matrix. I am using them as 
    %index to read the corresponding covariance value stored in the Cov
    %matrix
    covPair(2,1) = Cov(trial(i+5),trial(i));
    covPair(1,2) = Cov(trial(i+5),trial(i));
    covPair(2,2) = Cov(trial(i+5),trial(i+5));
    MeanPair(1) = MeanVector(trial(i));
    MeanPair(2) = MeanVector(trial(i+5));
    aPairSquare = (covPair(1,1)^2 + covPair(2,2)^2 - 2*covPair(1,2))/(MeanPair(1)-MeanPair(2))^2;
    riskPairMVP = (oneVector'* inv(covPair) * oneVector).^(-0.5);
    weightPairMVP = riskPairMVP.^2 * inv(covPair) * oneVector;
    returnPairMVP = weightPairMVP' * MeanPair;
    y(i,:) = sqrt((x.^2-riskPairMVP^2)/aPairSquare) + returnPairMVP; %equation for the parabala generated by the portfolio with two securities
    %I only draw the positive part of the hyperbola
end
figure
hold on
plot(x,y(1,:),'k')
plot(x,y(2,:),'y')
plot(x,y(3,:),'r')
plot(x,y(4,:),'g')
plot(x,y(5,:),'b')
xlabel('risk')
ylabel('return')
legend('sector 1 and 11','sector 3 and 14','sector 6 and 17','sector 10 and 19','sector 27 and 39')
title('Five pairs of securities')
hold off
%% Question C
%Plot for the efficient frontier
mTilda = zeros(48,2);
oneVector = ones(48,1);
mTilda(:,1) = MeanVector;
mTilda(:,2) = oneVector; %constructing the mTilda matrix
B = mTilda' * inv(Cov) * mTilda;
G = inv(B) * mTilda' * inv(Cov) * mTilda * inv(B);
detG = det(G);
figure
hold on
x = 0:0.01:2;
y = sqrt((x.^2 - 1/G(1)*detG)/G(1)) - G(3)/G(1);
plot(x,y,'k')
%plot for the line from (0,R) to S&P500 market portfolio
slopeSP500 = (ReturnSP500 - dailyR) / riskSP500;
plot(x, slopeSP500.*x+dailyR, 'r')
%plot for the line from (0,R) to theoratical market portfolio
meanExcess = MeanVector - dailyR;
weightMarket = 1/(oneVector' * inv(Cov) * meanExcess) * inv(Cov) * meanExcess; %Use formula to find the weight of the market porfolio
returnMarket = weightMarket' * MeanVector;
riskMarket = sqrt(weightMarket' * Cov * weightMarket);
slopeMarket = (returnMarket - dailyR) / riskMarket;
plot(x, slopeMarket.*x+dailyR, 'b')
xlabel('risk')
ylabel('return')
legend('Efficient frontier','line from (0,R) to S&P500','line from (0,R) to theoratical market')
hold off
%% Question D
mu = [0.34, 0.71, 1.52]; % Some random return I chose
risk = sqrt(G(1)*(mu + G(3)/G(1)).^2 + detG/G(1));
% Since the three return values I chose is 0.34, 0.71 and 1.52
% and the resulting risk is 1.197, 1.9813 and 3.8225
% so smaller return corresponds to smaller risk
weight = zeros(48,3); % To store the weight for three portfolios given return in the mu vector
for i = 1:3
    muTilda = [mu(i); 1];
    weight(:,i) = inv(Cov) * mTilda * inv(B) * muTilda;
end
weightOf1And3 = zeros(48,2);
weightOf1And3(:,1) = weight(:,1);
weightOf1And3(:,2) = weight(:,3);
weightOf2 = weight(:,2);
X = linsolve(weightOf1And3,weightOf2); %Solve a system of 2 linear equations
% AX = B, A is the weight of portfolio 1 and weight of portfolio 3. B is the 
% weight of portfolio 2. Since X is all positive, so portfolio 2 can be achieved 
% through a convex combination of portfolio 1 and portfolio 3
txt = ['Since the three return values I chose is ', num2str(mu(1)), ', ', num2str(mu(2)), ' and ', num2str(mu(3))];
txt1 = ['and the resulting risk is ', num2str(risk(1)), ', ', num2str(risk(2)), ' and ', num2str(risk(3))];
txt2 = ['so smaller return corresponds to smaller risk'];
disp(txt);
disp(txt1);
disp(txt2);
%% Question E
txt = ['Since the daily interest rate is ', num2str(dailyR), ' and the daily return for MVP is ', num2str(returnMVP), ' so R > muMVP'];
disp(txt);
% Since the daily interest rate is 0.0091612 and the daily return for MVP is -0.090807 so R > muMVP
% This means the assumption we have for the existance of theoratical market
% portfolio has failed
%% Quesiton F
figure
hold on
x = 0:0.01:2;
y = dailyR + (ReturnSP500-dailyR)/riskSP500*x; % market line from the result of S&P500
plot(x,y)
plot(x, slopeMarket.*x+dailyR, 'r') % market line from the theoratical result
hold off
xlabel('risk')
ylabel('return')
legend('Capital Market Line from S&P500', 'Theoratical Capital Market Line')
% Captial Market line from S&P500 outperforms the theoratical captial
% market line but that's because the interest rate beats the return for MVP
% The assumption for market line fails
%% Question G
figure
excessReturn = zeros(5,1);
excessRetrun(1) = returnMVP - returnMarket;
excessReturn(2:4) = mu - returnMarket;
excessReturn(5) = returnNaive - returnMarket;
beta = zeros(5,1);
for i = 1 : 5
    beta(i) = excessReturn(i) / riskMarket.^2;
end
returnG = zeros(5,1);
returnG = excessReturn + returnMarket;
plot(beta, returnG)
xlabel('beta')
ylabel('mu')
legend('Security Market Line')
%% Question H
weights = zeros(48,6);
weights(:,1) = weightMVP;
weights(:,2) = weightMarket;
weights(:,3) = weightNaive;
weights(:,4:6) = weight; %weight for the three portfolios chosen at question D
results = zeros(6, 251); % To store the daily results for these 6 portfolios
for i = 1 : 6
    for j = 1 : 251
        newweight = weights(:,i) .* A(:,j);
        results(i,j) = sum(newweight);
    end
end
x = 1:1:251;
figure
hold on
plot(x, results(1,:)) %MVP
plot(x, results(2,:)) %Theoratical Market Portfolio
plot(x, results(3,:)) %The Naive portfolio
plot(x, results(4,:)) %Portfolio 1 chosen at Question D
plot(x, results(5,:)) %Portfolio 2 chosen at Quesiton D
plot(x, results(6,:)) %Portfolio 3 chosen at Quesiton D
hold off
xlabel('day')
ylabel('return')
axis tight
legend('MVP portfolio','Theoratical market portfolio','Naive portfolio', 'Portfolio 1 chosen at Question D','Portfolio 2 chosen at Question D','Portfolio 3 chosen at Question D')
% The result of 2008 is a mess but that's expected. The daily interest rate
% for 2008 is higher than the return for MVP. There is no theoratical
% market portfolio.(The theoratical market portfolio intersects with the lower portion of the 
% hyperbola) The naive portfolio performs actually pretty well. Conclusion
% during financial crisis, theory falls apart and we should put everything
% in bank. 